# Generated by Django 5.0.14 on 2025-08-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, help_text='Username attempted (for failed logins)', max_length=150)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('password_changed', 'Password Changed'), ('role_changed', 'Role Changed')], help_text='Type of authentication action', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with the action (null for failed login attempts)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='auth_logs_user_id_237eb3_idx'), models.Index(fields=['action', '-timestamp'], name='auth_logs_action_730f41_idx'), models.Index(fields=['ip_address', '-timestamp'], name='auth_logs_ip_addr_e14d52_idx'), models.Index(fields=['success', '-timestamp'], name='auth_logs_success_e968d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(blank=True, help_text='Active role for this session', max_length=50)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Last login IP address for security tracking', null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Account lockout expiration time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_profile', models.OneToOneField(blank=True, help_text='Link to staff record', null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.staff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['staff_profile'], name='auth_user_p_staff_p_672ad0_idx'), models.Index(fields=['current_role'], name='auth_user_p_current_fa6f85_idx'), models.Index(fields=['account_locked_until'], name='auth_user_p_account_b6e5dc_idx')],
            },
        ),
    ]
